require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'config/environments/*'
    - 'config/routes.rb'

Layout/LineLength:
  Exclude:
    - 'config/routes.rb'
    - 'config/environments/*'

# コメントでASCII文字以外を使えなくする(trueだと日本語が使えない)
Style/AsciiComments:
  Enabled: false

# 複数行の引数、配列、ハッシュの最後にコンマを強制する
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# 関連付けのclass_nameオプションに文字列が渡されているかどうか
Rails/ReflectionClassName:
  Enabled: false

# Foo::Barみたいな書き方をしていないかどうか
Style/ClassAndModuleChildren:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_request
